CREATE TABLE "Roles" (
  "Role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" varchar(40) NOT NULL
);

CREATE TABLE "Users" (
  "User_Id" "int(pk, increment)",
  "Name" varchar(30) NOT NULL,
  "Email" varchar(50) NOT NULL,
  "Password" varchar(30) NOT NULL,
  "Age" int
);

CREATE TABLE "Courses" (
  "Course_Id" "int(pk, increment)",
  "Title" varchar(40) NOT NULL,
  "Description" TEXT,
  "Level" varchar(50),
  "Teacher" int
);

CREATE TABLE "Course_Videos" (
  "Video_Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Title" varchar(40),
  "Url" varchar(100) NOT NULL,
  "Course_Id" int
);

CREATE TABLE "Categories" (
  "Categories_Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" varchar(40) NOT NULL
);

CREATE TABLE "User_Roles" (
  "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID" INT,
  "RoleID" INT
);

ALTER TABLE "Courses" ADD FOREIGN KEY ("Teacher") REFERENCES "Users" ("User_Id");

ALTER TABLE "Course_Videos" ADD FOREIGN KEY ("Course_Id") REFERENCES "Courses" ("Course_Id");

ALTER TABLE "User_Roles" ADD FOREIGN KEY ("UserID") REFERENCES "Users" ("User_Id");

ALTER TABLE "User_Roles" ADD FOREIGN KEY ("RoleID") REFERENCES "Roles" ("Role_id");
